application: moneta
version: dev
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /styles
  static_dir: styles

- url: /views
  static_dir: views

- url: /.*
  script: _go_app
